version: '3.8'
services:
  app:
    container_name: schedular-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8080/api
    command: sh -c "npm install && npm run dev"
